version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.cloud
    environment:
      WWWUSER: 1001  # deploy's UID
    ports:
      - ${APP_PORT}:80
    volumes:
      - .:/var/www/html
      - ${APP_DATA_DIR}/app/storage:/var/www/html/storage
      - ${APP_DATA_DIR}/app/bootstrap/cache:/var/www/html/bootstrap/cache
    depends_on:
      - mysql
      - redis
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
    restart: always

  redis:
    image: redis:7-alpine
    volumes:
      - ${APP_DATA_DIR}/redis/data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    restart: always

  meilisearch:
    image: 'getmeili/meilisearch:v0.28'
    volumes:
      - ${APP_DATA_DIR}/meilisearch/data.ms:/data.ms
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
      retries: 3
      timeout: 5s
    restart: always
