name: PHP Analysis

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  php-analysis:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    name: Analyse - PHP 8.1

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
    - uses: actions/checkout@v2
    - name: Cache Composer packages
      uses: actions/cache@v2
      with:
        path: vendor
        key: php-${{ hashFiles('**/composer.lock') }}
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Perform static analysis
      run: composer lint
