name: Refresh Dev

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  refresh:
    if: github.repository == 'fluid-project/lcil'

    runs-on: ubuntu-latest

    concurrency: deploy-dev

    steps:
      - name: Refresh database
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          proxy_host: ${{ secrets.SSH_PROXY_HOSTNAME }}
          proxy_username: ${{ secrets.SSH_PROXY_USERNAME }}
          proxy_key: ${{ secrets.SSH_PROXY_PRIVATE_KEY }}
          proxy_port: ${{ secrets.SSH_PROXY_PORT }}
          script: |
            cd /srv/fluid-lcil-dev && \
            git checkout -f && \
            git checkout dev && \
            git pull && \
            ./bin/refresh-dev.sh

      - name: Wait
        run: sleep 15

      - name: Smoke test
        run: curl --location --no-buffer --retry 120 --retry-delay 1 https://lcil-dev.fluidproject.org
